# Site settings
baseurl = "http://joshmatz.com/"
languageCode = "en-us"
title = "Josh Matz"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "joshmatz"
canonifyurls: true
publishdir: "public"

[params]
  name = "Josh Matz"
  description = ""
  bio = "Design - Engineering - Product"
  # Enter optionally your twitter account
  twitter = "joshmatz"
  enableRSS = true

  # Add custom assets with their paths relative to the static folder
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  about = ""
  subscribe = ""
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = ""
  # Sharing options and author information in posts
  aboutAuthor = "Design, development, products, culture"
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/joshmatz"
    linkedin  = "https://www.linkedin.com/in/joshmatz"
    github   = "https://www.github.com/joshmatz"
    dribble  = "https://www.dribbble.com/joshmatz"
